### ISSUE TITLE
[CEPH] Summarize CRUSH rules and Pool/Rule relationships in output

### ISSUE THREAD

**Issue by KellenRenshaw** [canonical/hotsos#170]
All data can be found in "ceph report" output.

For quick analysis, it would be useful to extract the CRUSH rules and list pools using each rule in the rule entry.

Rules example from ceph report:
```json
        "rules": [
            {
                "rule_id": 0,
                "rule_name": "replicated_rule",
                "ruleset": 0,
                "type": 1,
                "min_size": 1,
                "max_size": 10,
                "steps": [
                    {
                        "op": "take",
                        "item": -1,
                        "item_name": "default"
                    },
                    {
                        "op": "chooseleaf_firstn",
                        "num": 0,
                        "type": "rack"
                    },
                    {
                        "op": "emit"
                    }
                ]
            },
            {
                "rule_id": 1,
                "rule_name": "flash-pool",
                "ruleset": 1,
                "type": 1,
                "min_size": 1,
                "max_size": 10,
                "steps": [
                    {
                        "op": "take",
                        "item": -2,
                        "item_name": "default~ssd"
                    },
                    {
                        "op": "chooseleaf_firstn",
                        "num": 0,
                        "type": "rack"
                    },
                    {
                        "op": "emit"
                    }
                ]
            },
            {
                "rule_id": 2,
                "rule_name": "hybrid-pool",
                "ruleset": 2,
                "type": 1,
                "min_size": 1,
                "max_size": 10,
                "steps": [
                    {
                        "op": "take",
                        "item": -30,
                        "item_name": "default~hdd"
                    },
                    {
                        "op": "chooseleaf_firstn",
                        "num": 0,
                        "type": "rack"
                    },
                    {
                        "op": "emit"
                    }
                ]
            }
        ],
```

The "rule_id" value is used in the pool's configuration as the value in the "crush_rule" key/value pair.

Mockup of potential output
```yaml
crush rules:
  "replicated_rule":
    id: 0
    type: replicated
    pools: [ cinder-ceph, cinder-ceph-coolstuff ]
  "flash-pool":
    id: 1
    type: replicated
    pools: [ cinder-ceph-vroom ]
  "hybrid-pool":
    id: 2
    type: replicated
    pools: [ ]
```

**Comment by hillpd** [comment]
This would definitely come in handy. I'd recommend adding the pool id to the list for quick reference.

Example:
```yaml
crush rules:
  "replicated_rule":
    id: 0
    type: replicated
    pools: [ cinder-ceph (8), cinder-ceph-coolstuff (9)]
  "flash-pool":
    id: 1
    type: replicated
    pools: [ cinder-ceph-vroom (20) ]
  "hybrid-pool":
    id: 2
    type: replicated
    pools: [ ]
```
