### ISSUE TITLE
check for "experiencing BlueFS spillover" in ceph

### ISSUE THREAD

**Issue by nkshirsagar** [canonical/hotsos#258]
as described in https://tracker.ceph.com/issues/38745 , and case 00326782, hotsos should check for message "BlueFS spillover detected " to check for the rocksdb's level-sized issue.

$ ceph -s
  cluster:
    id:     815ea021-7839-4a63-9dc1-14f8c5feecc6
    health: HEALTH_WARN
            BlueFS spillover detected on 1 OSD(s) <--

Also, even if this situation has not been hit, we should check between ceph-osd versions 15.2.6->15.2.10 if the option bluestore_volume_selection_policy is not set to "use_some_extra" because then the vulnerability still exists.

So this is the second check to be made, to check for the vulnerability if the ceph packages fall between 15.2.6 and 15.2.10,

$ sudo ceph daemon osd.1 config show|grep -i policy
"bluestore_volume_selection_policy": "use_some_extra",

**Comment by dosaboy** [comment]
The following can be used as a guide on how to implement this:
https://github.com/canonical/hotsos/blob/master/defs/scenarios/storage/ceph/auth_insecure_global_id_reclaim_allowed.yaml

**Comment by nkshirsagar** [comment]
There are two parts to this check.

a) simply check if we see BlueFS spillover detected in the ceph status, or the detailed status, and report the bug if that string is found.

b) Check between ceph-osd versions 15.2.6->15.2.10 to see if bluestore_volume_selection_policy is not set to use_some_extra and if that is the case, report the vulnerability.

I can see that a) is easily implemented using the approach shown in https://github.com/canonical/hotsos/blob/master/defs/scenarios/storage/ceph/auth_insecure_global_id_reclaim_allowed.yaml but I am not sure if the scenarios can also take min-version, fixed-version, etc like how the bugs do, and how I'd check for the value of bluestore_volume_selection_policy. Would I need to add a property to the class CephMon(CephDaemonBase) and return that value? just like we do for osdmaps_count?

```
class CephMon(CephDaemonBase):

    def __init__(self):
        super().__init__('mon')

    @property
    def osdmaps_count(self):
        report = self.cli.ceph_report_json_decoded()
        if not report:
            return 0

        try:
            return len(report['osdmap_manifest']['pinned_maps'])
        except (ValueError, KeyError):
            return 0
```

**Comment by dosaboy** [comment]
@nkshirsagar so you can implement this is one of two ways; either using bugs (i have added support for the [requires](https://github.com/canonical/hotsos/tree/master/defs#requires) property to bugchecks [1]) or as a scenario. If you use a scenario you will need to implement all the requirements as properties (which you can then call using the [requires](https://github.com/canonical/hotsos/tree/master/defs#requires) property). Its up to you which one fits best.

[1] https://github.com/canonical/hotsos/tree/master/defs#bugs

**Comment by nkshirsagar** [comment]
thank you for https://github.com/canonical/hotsos/pull/273/files @dosaboy++  

I am trying to consume it this way, as a command, with both the A and B parts defined in bugs/storage/ceph.yaml , with one bug check under 38745 ,and the vulnerability under  vulnerable_to_38745

```
38745:
  settings:
    package: 'ceph-osd'
  input:
    command: ceph_health_detail_json_decoded
  expr: '.+BlueFS spillover detected on'
  hint: 'spillover'
  raises:
    message: >-
      installed package '{package_name}' with version {version_current} has a
      known bug https://tracker.ceph.com/issues/38745.
vulnerable_to_38745:
  input:
    command: ceph_daemon_config_show
    options:
      kwargs:
        name: 'bluestore_volume_selection_policy'
    value: 'use_some_extra'
    operator: ne
  settings:
    package: 'ceph-osd'
    versions-affected:
      - min-broken: 15.2.6
        min-fixed: 15.2.11
  raises:
    message: >-
      Vulnerability to a known bug https://tracker.ceph.com/issues/38745.
      Please set bluestore_volume_selection_policy of all OSDs to use_some_extra
```
