### ISSUE TITLE
Multiple operators of same type are not properly handled in requires

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/hotsos#276]
In requires section, if you specify multiple operators of same type then its not properly handled.
The operators in require section work correctly only when the operators of each type are specified only once.

For example, below are 4 properties with 2 or operators. Lets say results of each property are R1, R2, R3, R4.
As per existing code, it is evaluated to OR( R1, R2, R3, R4)
The expectation is  AND( OR(R1, R2), OR(R3, R4) )

```
<bug id>:
  requires:
    or:
      - property: P1
        value: [V1]
        operator: ne
      - property: P2
        value: [V2]
        operator: ne
    or:
      - property: P3
        value: [V3]
        operator: ne
      - property: P4
        value: [V4]
        operator: ne
```

The operations are handled after all properties are evaluated instead of for each operation [1]. 
The should be handled per each operation.

[1] https://github.com/canonical/hotsos/blob/master/core/ycheck/__init__.py#L524-L534
