### ISSUE TITLE
Teach sysctl plugin about comments!

### ISSUE THREAD

**Issue by pponnuvel** [canonical/hotsos#533]
```
  sysctl-mismatch:
    vm.swappiness:
      actual: '30'
      expected: '30 # default value is 60' 
```
