### ISSUE TITLE
Make 'max' value optional in APT check

### ISSUE THREAD

**Issue by pponnuvel** [canonical/hotsos#585]
The APT check requires a min *and* max values forcing checks to be written like:

```
   apt:
      ceph-osd:
        - min: 14.2.0
          max: 100.0.0
```

to mean "14.2.0 or newer". It should be modified to treat max as optional.
