### ISSUE TITLE
Detect repeated ovn leader elections

### ISSUE THREAD

**Issue by nicolasbock** [canonical/hotsos#596]
We have seen a few cases now where `ovn` decides to frequently run leader
elections. The log files will include lines such as

```
[sosreport-juju-23df31-39-lxd-25-00359661-2023-05-06-owhfskk]/ovsdb-server-nb.log     |2023-05-06T17:28:09.803Z|21486|raft|INFO|term 3090: 1083 ms timeout expired, starting election
[sosreport-juju-23df31-38-lxd-26-00359661-2023-05-06-vsebghl]/ovsdb-server-nb.log     |2023-05-06T17:28:19.657Z|21393|raft|INFO|term 3091: 1024 ms timeout expired, starting election
[sosreport-juju-23df31-39-lxd-25-00359661-2023-05-06-owhfskk]/ovsdb-server-nb.log     |2023-05-06T17:29:00.454Z|21547|raft|INFO|term 3097: 1132 ms timeout expired, starting election
[sosreport-juju-23df31-40-lxd-25-00359661-2023-05-06-tbilkzx]/ovsdb-server-nb.log     |2023-05-06T17:29:14.288Z|17791|raft|INFO|term 3098: 1436 ms timeout expired, starting election
[sosreport-juju-23df31-38-lxd-26-00359661-2023-05-06-vsebghl]/ovsdb-server-nb.log     |2023-05-06T17:29:23.328Z|21476|raft|INFO|term 3099: 1091 ms timeout expired, starting election
[sosreport-juju-23df31-40-lxd-25-00359661-2023-05-06-tbilkzx]/ovsdb-server-nb.log     |2023-05-06T17:29:54.265Z|17840|raft|INFO|term 3103: 1312 ms timeout expired, starting election
[sosreport-juju-23df31-39-lxd-25-00359661-2023-05-06-owhfskk]/ovsdb-server-sb.log     |2023-05-06T17:29:57.105Z|03617|raft|INFO|term 185: 1685 ms timeout expired, starting election
```

`hotsos` should flag this issue and suggest remedies:

```
sosreport:
  potential-issues:
    multiple ovsdb elections detected. This can be caused by insufficient polling timeout settings. Verify that....
openvswitch:
  ovn-checks:
    ovsdb-server-nb:
      started-election:
        '2023-05-06': 12345
```
