### ISSUE TITLE
Flagging suspicious resource usage

### ISSUE THREAD

**Issue by nishant-dash** [canonical/hotsos#634]
This is a bit tricky, but I was wondering if it was possible to detect absurd resource usage of certain services.

For example, if I run `hotsos --openvswitch` on a  `ovn-central` unit, hotsos lists all the relevant services as such,
```yaml
openvswitch:
  services:
    systemd:
      enabled:
        - ovn-central
        - ovn-nb-ovsdb
        - ovn-ovsdb-server-nb
        - ovn-ovsdb-server-sb
        - ovn-sb-ovsdb
      static:
        - ovn-northd
    ps:
      - ovn-northd (1)
      - ovsdb-server (2)
```

But taking it a step further, looking at northd shows us
```console
   Main PID: 1385650 (ovn-northd)
      Tasks: 3 (limit: 463832)
     Memory: 255.6G
```

Defining limits for a variety of services is indeed  very tricky, but I feel that there are certain values which are high enough to definitely be a red flag.
