### ISSUE TITLE
Trying to create a hotsos check for lp1940549 

### ISSUE THREAD

**Issue by 106106** [canonical/hotsos#715]
Hi hotsos team,

I'm trying to create a check for lp1940549. Essentially just looking for the vault snap on version less than 1.7. Here's what I have so far:

```
checks:
  has_lp1940549:
    snap:
      vault:
        # Looking for version less than 1.7
        - min: 1967
          max: 2039
conclusions:
  lp1940549:
    decision:
      - has_lp1940549
    raises:
      type: LaunchpadBug
      bug-id: 1940549
      message: >-
        Vault may not renewed or reissued certificates. This may
        lead to other services being degraded due to TLS issues.
        Upgrade to channel 1.7 or later. See the knowledge base
        article Vault HA cluster upgrade with Juju for upgrade steps.
```

I'm trying to check it on a sosreport that I know has version 1.5.9 of vault with:
```
hotsos --defs-path ~/ sosreport-vault.tar.xz
hotsos --defs-path ~/test.yaml sosreport-vault.tar.xz
```
But no luck. Any pointer would be appreciated.
Thanks!
