### ISSUE TITLE
Fix the check for openvswitch/ovn/ovn_db_upgrade/has_northd_version_mismatch

### ISSUE THREAD

**Issue by adilcan** [canonical/hotsos#719]
Hi,

After an OVN package upgrade, some OVN-based clouds experienced a network outage.

An example warning from /var/log/ovn/ovn-controller.log is below:

`2023-09-06T08:31:20.060Z|00263|main|WARN|controller version - 22.03.2-20.21.0-61.4 mismatch with northd version - 22.03.0-20.21.0-58.3`

We already have a scenario for this in `/hotsos/defs/scenarios/openvswitch/ovn/ovn_db_upgrade.yaml`:

```
  has_northd_version_mismatch:
    input: var/log/ovn/ovn-controller.log
    expr: '([\d-]+)T([\d:]+)\.\d+Z\|\S+\|main\|WARN\|controller version - (\S+) mismatch with northd version - (\S+)'
    constraints:
```
However, when I run hotsos on the sosreport containing the warning, ignores it:
```
...
ovn-match-northd-version: 'true'
...
```

This could be caused by the `ovn-host:max` value in `ovn_db_upgrade.yaml`:

```
  ovn_controller_not_fixed:
    apt:
      ovn-host:
        - min: 0
          max: 20.03.2-0ubuntu0.20.04.3
...          
conclusions:
  has_northd_version_mismatch:
    decision:
      - is_ovn_controller
      - ovn_controller_not_fixed
      - has_northd_version_mismatch
```

If you need the sosreport please contact me on mattermost.

Thanks and best regards,
adilcan
