### ISSUE TITLE
Add more comparison operators to package version checks

### ISSUE THREAD

**Issue by mustafakemalgilor** [canonical/hotsos#766]
As of now, we have `min` and `max` at our disposal for package version checks (e.g. apt):

```yaml
checks:
  has_buggy_keystone_version:
    apt:
      keystone:
        # Ussuri
        - min: 2:17.0.0
          max: 2:17.0.0-99
```

I think having more operators (e.g. eq(=), gt(>), gte(>=), lt(<), lte(<=)) would make specifying version ranges easier. (especially lt & gt since min & max are already equivalent to lte&gte)

```yaml
checks:
  has_buggy_keystone_version:
    apt:
      keystone:
        # Ussuri
        - gte: 2:17.0.0
          lt: 2:17.0.1
```
... or

```yaml
checks:
  has_buggy_keystone_version:
    apt:
      keystone:
        # Ussuri
        - '>=': 2:17.0.0
          '<': 2:17.0.1
```
