### ISSUE TITLE
microceph is missing `local-osds` and `ps` sections

### ISSUE THREAD

**Issue by pponnuvel** [canonical/hotsos#804]
1. `local-osds` section is missing because Microceph doesn't use ceph-volume. This section outputs:
```
    local-osds:
      2:
        fsid: 831fa05a-3901-4206-a850-ac38d26327d2
        dev: /dev/vdb
        rss: 217M
```

2. `ps` section provides:
```
      ps:
        - ceph-crash (1)
        - ceph-osd (1)
```

We should be able to get data for both section by different means for Microceph.

Output from a standard ceph deployment: https://pastebin.canonical.com/p/VzX5g6Xq8h/
