### ISSUE TITLE
microceph support

### ISSUE THREAD

**Issue by nishant-dash** [canonical/hotsos#903]
currently running hotsos with the `--storage` plugin gives me
```yaml
storage:
  ceph:
    release:
      name: unknown
      days-to-eol: null
    services:
      systemd:
        disabled:
          - ceph-volume
        mds:
          - snap.microceph.mds
        mgr:
          - snap.microceph.mgr
        mon:
          - snap.microceph.mon
        osd:
          - snap.microceph.osd
        rgw:
          - snap.microceph.rgw
      ps:
        - ceph-mds (1)
        - ceph-mgr (1)
        - ceph-mon (1)
        - ceph-osd (2)
    dpkg:
      - ceph-volume 17.2.7-0ubuntu0.22.04.1
    snaps:
      - microceph 0+git.4a608fc
    status: HEALTH_OK
    versions:
      mon:
        - 17.2.6
      mgr:
        - 17.2.6
      osd:
        - 17.2.6
      mds:
        - 17.2.6
```

it would be great if we can add more to this to get it upto parity with regular ceph
